name: Build Nightly APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: all-apks
        path: '**/build/outputs/apk/debug/*.apk'
